### ISSUE TITLE
OKTW MissileReturn

### ISSUE THREAD

**Issue by Pikachu7** [berbb/PortAIO#115]
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at OneKeyToWin_AIO_Sebby.Core.MissileReturn.CalculateReturnPos()
   at OneKeyToWin_AIO_Sebby.Core.MissileReturn.Game_OnGameUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

**Comment by berbb** [comment]
Should be okay now.
