### ISSUE TITLE
OKTW Thresh LogicW

### ISSUE THREAD

**Issue by Pikachu7** [berbb/PortAIO#121]
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.Common.PredictionOutput.get_CastPosition()
   at OneKeyToWin_AIO_Sebby.Champions.Thresh.LogicW()
   at OneKeyToWin_AIO_Sebby.Champions.Thresh.Game_OnGameUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

**Comment by berbb** [comment]
Should be fixed.
