### ISSUE TITLE
Nidalee

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO#180]
`Cannot prepare RenderObjects for drawing. Ex:System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at LeagueSharp.Common.Render.PrepareObjects()`

```
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at KurisuNidalee.KurisuLib.CanUse(Spell spell, Boolean human, String mode)
   at KurisuNidalee.CastManager.SwitchForm(Obj_AI_Base target, String mode)
   at KurisuNidalee.KurisuNidalee.Harass()
   at KurisuNidalee.KurisuNidalee.Game_OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()

```

```
Exception occured! EloBuddy might crash!

Type: System.InvalidCastException
Message: Unable to cast object of type 'EloBuddy.AIHeroClient' to type 'EloBuddy.Obj_AI_Minion'.

Stracktrace:
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KurisuNidalee.CastManager.CastJavelin(Obj_AI_Base target, String mode)
   at KurisuNidalee.KurisuNidalee.Combo()
   at KurisuNidalee.KurisuNidalee.Game_OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
```

**Comment by berbb** [comment]
1st error shouldn't have an impact on the game at all. But I pushed an update that should fix the bottom two.
