### ISSUE TITLE
valvaresharp zed crashes upon pressing space

### ISSUE THREAD

**Issue by SnowDenix** [berbb/PortAIO#184]

**Comment by Lemonadez** [comment]
No it doesnt..Im pressing Space and I dont crash at all. I think you need to clear your AppData and do fresh installation. But here are some problem that show on console.


```
Exception occured! EloBuddy might crash!
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at Zed.Program.Combo(AIHeroClient t)
   at Zed.Program.Game_OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
```

**Comment by berbb** [comment]
Valvrave is known to crash and I haven't figured out a way to fix it yet.
