### ISSUE TITLE
Kalista

### ISSUE THREAD

**Issue by romonlol** [berbb/PortAIO#191]
So here bunch of exceptions.( clear app data and bordeless mode)
```
System.Runtime.InteropServices.SEHException:` External component has thrown an exception.
   at _strcmpi(SByte* , SByte* )
   at EloBuddy.Obj_AI_Base.HasBuff(String name)
   at LeagueSharp.Common.Interrupter.<>c__DisplayClass7_0.<IsChannelingImportantSpell>b__0(InterruptableSpell spell)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at LeagueSharp.Common.Interrupter.IsChannelingImportantSpell(AIHeroClient unit)
   at SPrediction.Prediction.GetFastUnitPosition(Obj_AI_Base target, Single delay, Single missileSpeed, Nullable`1 from, Single distanceSet)
   at SPrediction.Collision.<>c__DisplayClass13_0.<GetCollisions>b__1(AIHeroClient p)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.CountAggregationOperator`1.CountAggregationOperatorEnumerator`1.MoveNextCore(Int32& currentElement)
   at System.Linq.Parallel.InlinedAggregationOperatorEnumerator`1.MoveNext(TIntermediate& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c__DisplayClass0.<_cctor>b__1(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at `System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`
```

Game just freeze during team fight , using Ikalista, EzEvade,trackers, spredicrioner

```
[8:51:39 - Error] InnerException(s):
[8:51:39 - Error] ---------------------------------------------------
[8:51:39 - Error] Type: System.NullReferenceException
[8:51:39 - Error] Message: Object reference not set to an instance of an object.
[8:51:39 - Error]
[8:51:39 - Error] Stracktrace:
[8:51:39 - Error]    at Challenger_Series.Plugins.Kalista.QLogic(AttackableUnit target)
   at Challenger_Series.Plugins.Kalista.Orbwalker_OnPostAttack(AttackableUnit target, EventArgs args)
[8:51:39 - Error] ---------------------------------------------------
[8:51:39 - Error] ===================================================
[8:51:39 - Error]
[8:51:40 - Error]
[8:51:40 - Error] ===================================================
[8:51:40 - Error] Failed to notify Orbwalker.OnPostAttack event listener!
[8:51:40 - Error]
[8:51:40 - Error] Stacktrace of the Exception:
[8:51:40 - Error]
[8:51:40 - Error] Type: System.Reflection.TargetInvocationException
[8:51:40 - Error] Message: Exception has been thrown by the target of an invocation.
[8:51:40 - Error]
[8:51:40 - Error] Stracktrace:
[8:51:40 - Error]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at EloBuddy.SDK.Orbwalker.NotifyEventListeners(String eventName, Delegate[] invocationList, Object[] args)
```
Challenger kalista EzEvade SebbyBW, trackers.spredicrioner

```
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at SebbyLib.Movement.PredictionOutput.get_CastPosition()
   at SPredictioner.EventHandlers.Spellbook_OnCastSpell(Spellbook sender, SpellbookCastSpellEventArgs args)
   at EloBuddy.Spellbook.OnSpellbookCastSpellNative(Obj_AI_Base* A_0, Spellbook* A_1, Vector3f* A_2, Vector3f* A_3, UInt32 A_4, Int32 A_5)
```

Ikalista reborn sebbyBW EzEvade and trackers.spredicrioner

Next thing is Kalista rend calculation totally broken in every addon. I tried 50 90 150 300 rend damage reduction and it cant even smite properly dragon ( left 1100 hp), or scatter crab, same with champions and siege minions. Regular range and melee minions is ok.

Sebby ban war looks broken, during combo it randomly stop any action like orbwalk or spell cast and never enable it, you must press space again.

**Comment by berbb** [comment]
Jesus, this is illegible. I'll see what I can do.

**Comment by berbb** [comment]
Alright for the first error, when using the Kalista w/ Sprediction, goto the menu and switch it to Common instead. As for Sebby's Ban Wars, the Orbwalker breaks also happen on the original assembly, just use the standard Humanizer while you wait for me to port any fixes Sebby has made.
