### ISSUE TITLE
Orbwalker

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#203]
2 orbwalkers load even tho i tick off L# orbwalker and it just does nothing.

Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at SCommon.TS.ConfigMenu.getCheckBoxItem(String item)
   at SCommon.TS.TargetSelector.Drawing_OnDraw(EventArgs args)
   at EloBuddy.Drawing.OnDrawingDrawNative()

**Comment by SidaRevamped** [comment]
same problem

**Comment by berbb** [comment]
Fixed.
