### ISSUE TITLE
el rengar bug

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#235]
Hi el rengar doesnt use AA sometimes there is the console error
 at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
System.NullReferenceException: Object reference not set to an instance of an object.
   at ElRengarRevamped.MenuInit.getCheckBoxItem(Menu m, String item)
   at ElRengarRevamped.ActiveModes.Combo()
Ty for portaio

**Comment by berbb** [comment]
Fixed.
