### ISSUE TITLE
Valvravelee sin bug

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#236]
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.SDK.PredictionOutput.get_UnitPosition()
   at Valvrave_Sharp.Plugin.LeeSin.<>c.<KillSteal>b__51_0(AIHeroClient x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Valvrave_Sharp.Plugin.LeeSin.KillSteal()
   at Valvrave_Sharp.Plugin.LeeSin.OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

Happen when u chase an enemy ad lee try to Q

Ty for portaio

**Comment by inphratiic** [comment]
it's a known issue, they working on a fix

**Comment by IlikeBaconLol** [comment]
No the famous issue is about the Q drawing, there its the Q prediction different

**Comment by IlikeBaconLol** [comment]
Or i'm just totaly dumb ?
Should i close the issue @Muse30 @berbb ?

**Comment by Muse30** [comment]
is the same issue actually... really hard to find a fix for this but berbb is probably looking for one
