### ISSUE TITLE
EBDickTion

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO#319]
I was using Ahri, with 
OKTW (Prediction No. 3 - SDK)
SDKPrediction Enable
EBPredictioner Enable,

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The provided unique menu id is already given!
Parameter name: sdkpaksldjaskdjlkasjdk
   at EloBuddy.SDK.Menu.MainMenu.AddMenu(String displayName, String uniqueMenuId, String longTitle)
   at EBPredictioner.SPredictioner.Initialize()
   at EBPredictioner.EventHandlers.Game_OnGameLoad(EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at LeagueSharp.Common.CustomEvents.Game.Game_OnGameStart(EventArgs args)

```

**Comment by KiriharaSenpai** [comment]
dont enable two predictioner at one time disable one of them then press f5

**Comment by berbb** [comment]
@KiriharaSenpai ^^

Don't have 2 predictions enabled.
