### ISSUE TITLE
ElUtilitySuite.Items.Zhonya

### ISSUE THREAD

**Issue by Pikachu7** [berbb/PortAIO#335]
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at ElUtilitySuite.Items.Zhonya.getCheckBoxItem(Menu m, String item)
   at ElUtilitySuite.Items.Zhonya.GameObjectOnCreate(GameObject sender, EventArgs args)
   at EloBuddy.GameObject.OnGameObjectCreateNative(GameObject* unit)
========================================

**Comment by berbb** [comment]
Fixed.
