### ISSUE TITLE
Karma

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO#34]
This is what I get from Console Spam.

```
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at Karma.Program.Drawing_OnDraw(EventArgs args)
   at EloBuddy.Drawing.OnDrawingDrawNative()

```

**Comment by berbb** [comment]
Fixed.
