### ISSUE TITLE
Underrated Garen errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#344]
[20:46:55 - Error]
[20:46:55 - Error] ===================================================
[20:46:55 - Error] Failed to notify Orbwalker.OnPostAttack event listener!
[20:46:55 - Error]
[20:46:55 - Error] Stacktrace of the Exception:
[20:46:55 - Error]
[20:46:55 - Error] Type: System.Reflection.TargetInvocationException
[20:46:55 - Error] Message: Exception has been thrown by the target of an invocation.
[20:46:55 - Error]
[20:46:55 - Error] Stracktrace:
[20:46:55 - Error]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at EloBuddy.SDK.Orbwalker.NotifyEventListeners(String eventName, Delegate[] invocationList, Object[] args)
[20:46:55 - Error]
[20:46:55 - Error] InnerException(s):
[20:46:55 - Error] ---------------------------------------------------
[20:46:55 - Error] Type: System.NullReferenceException
[20:46:55 - Error] Message: Object reference not set to an instance of an object.
[20:46:55 - Error]
[20:46:55 - Error] Stracktrace:
[20:46:55 - Error]    at UnderratedAIO.Champions.Garen.AfterAttack(AttackableUnit target, EventArgs args)
[20:46:55 - Error] ---------------------------------------------------
[20:46:55 - Error] ===================================================

**Comment by berbb** [comment]
Fixed, shouldn't be happening anymore.
