### ISSUE TITLE
Ahri

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO#37]
In Middle of team fight when opponent Malph my client just frozen and This what Appear on my Console. I was using  OKTW Prediction <- dont know if that matters what kind of prediction i Used.

```
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at OneKeyToWin_AIO_Sebby.Champions.Ahri.getCheckBoxItem(Menu m, String item)
   at OneKeyToWin_AIO_Sebby.Champions.Ahri.AntiGapcloser_OnEnemyGapcloser(ActiveGapcloser gapcloser)
   at LeagueSharp.Common.AntiGapcloser.Game_OnGameUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
```

**Comment by berbb** [comment]
Fixed the Console Error.
