### ISSUE TITLE
Alistar errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#383]
System.NullReferenceException: Object reference not set to an instance of an object.
   at PortAIO.Champion.Alistar.Program.HandleIgnite()
System.NullReferenceException: Object reference not set to an instance of an object.
   at PortAIO.Champion.Alistar.Program.HandleIgnite()
System.NullReferenceException: Object reference not set to an instance of an object.
   at PortAIO.Champion.Alistar.Program.HandleIgnite()
System.NullReferenceException: Object reference not set to an instance of an object.
   at PortAIO.Champion.Alistar.Program.HandleIgnite()
System.NullReferenceException: Object reference not set to an instance of an object.
   at PortAIO.Champion.Alistar.Program.HandleIgnite()

**Comment by berbb** [comment]
Fixed.
