### ISSUE TITLE
Taric Stracktrace

### ISSUE THREAD

**Issue by romonlol** [berbb/PortAIO#434]
` at SkyLv_Taric.CastOnDash.Unit_OnDash(Obj_AI_Base sender, DashItem args)
   at LeagueSharp.Common.CustomEvents.Unit.TriggerOnDash(Obj_AI_Base sender, DashItem args)
   at LeagueSharp.Common.Dash.ObjAiHeroOnOnNewPath(Obj_AI_Base sender, GameObjectNewPathEventArgs args)
   at EloBuddy.Obj_AI_Base.OnObj_AI_BaseNewPathNative(Obj_AI_Base* A_0, vector<EloBuddy::Native::Vector3f\,std::allocator<EloBuddy::Native::Vector3f> >* A_1, Boolean A_2, Single A_3)`

`   at SkyLv_Taric.Interrupter.Interrupter2_OnInterruptableTarget(AIHeroClient sender, InterruptableTargetEventArgs args)
   at LeagueSharp.Common.Interrupter2.<>c.<Game_OnGameUpdate>b__16_1(AIHeroClient enemy)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at LeagueSharp.Common.Interrupter2.Game_OnGameUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()`

**Comment by berbb** [comment]
This error shouldn't be harmful but I pushed updates that should fix this. But the fixed won't be in PortAIO, it'll be in Berb.Common so make sure to update that.
