### ISSUE TITLE
[OKTW/Exor] Corki errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#436]
Exception occured! EloBuddy might crash!

Type: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.

Stracktrace:
   at LeagueSharp.Common.Damage.<>c.<.cctor>b__4_492(Obj_AI_Base source, Obj_AI_Base target, Int32 level)
   at LeagueSharp.Common.Damage.GetDamageSpell(AIHeroClient source, Obj_AI_Base target, SpellSlot slot, Int32 stage)
   at LeagueSharp.Common.Damage.<>c__DisplayClass12_0.<GetDamageSpell>b__1(SpellDataInst spell)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LeagueSharp.Common.Damage.GetDamageSpell(Obj_AI_Base source, Obj_AI_Base target, String spellName)
   at LeagueSharp.Common.Damage.LSGetSpellDamage(Obj_AI_Base source, Obj_AI_Base target, String spellName)
   at SebbyLib.OktwCommon.Obj_AI_Base_OnProcessSpellCast(Obj_AI_Base sender, GameObjectProcessSpellCastEventArgs args)
   at EloBuddy.Obj_AI_Base.OnObj_AI_ProcessSpellCastNative(Obj_AI_Base* __unnamed000, SpellCastInfo* castInfo)
========================================

Also misses creeps a bit so I guess it's Berb.Common thing

Also, Exor Corki seems not to be using E when in combo

**Comment by berbb** [comment]
Fixed.
