### ISSUE TITLE
Valvrave Lee console errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#455]
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at Valvrave_Sharp.Plugin.LeeSin.getKeyBindItem(Menu m, String item)
   at Valvrave_Sharp.Plugin.LeeSin.OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

The insec seems not to work

**Comment by berbb** [comment]
Updated, should work now.
