### ISSUE TITLE
Jhin issue 

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#461]
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.Common.Spell.CastOnUnit(Obj_AI_Base unit, Boolean packetCast)
   at Jhin___The_Virtuoso.Modes.Clear.ExecuteQ()
   at Jhin___The_Virtuoso.Modes.Clear.ExecuteClear()
   at Jhin___The_Virtuoso.Jhin.JhinOnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================
struggling and doing strangemove AA cancel

**Comment by berbb** [comment]
Fixed. As for the AA cancel, that's EB's Orbwalker.

**Comment by IlikeBaconLol** [comment]
Windup i guess
