### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Lemonadez** [berbb/PortAIO#47]
Was playing Ahri or Sivir. Sometimes I get this error on console.

```
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at OneKeyToWin_AIO_Sebby.Core.MissileReturn.CalculateReturnPos()
   at OneKeyToWin_AIO_Sebby.Core.MissileReturn.Game_OnGameUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()




Stracktrace:
   at LeagueSharp.Common.Damage.<>c.<.cctor>b__4_492(Obj_AI_Base source, Obj_AI_Base target, Int32 level)
   at LeagueSharp.Common.Damage.GetDamageSpell(AIHeroClient source, Obj_AI_Base target, SpellSlot slot, Int32 stage)
   at LeagueSharp.Common.Damage.<>c__DisplayClass12_0.<GetDamageSpell>b__1(SpellDataInst spell)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LeagueSharp.Common.Damage.GetDamageSpell(Obj_AI_Base source, Obj_AI_Base target, String spellName)
   at LeagueSharp.Common.Damage.LSGetSpellDamage(Obj_AI_Base source, Obj_AI_Base target, String spellName)
   at SebbyLib.OktwCommon.Obj_AI_Base_OnProcessSpellCast(Obj_AI_Base sender, GameObjectProcessSpellCastEventArgs args)
   at EloBuddy.Obj_AI_Base.OnObj_AI_ProcessSpellCastNative(Obj_AI_Base* __unnamed000, SpellCastInfo* castInfo)
```

**Comment by berbb** [comment]
Should be fixed now.
