### ISSUE TITLE
OKTW twitch issue

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#481]
========================================
Exception occured! EloBuddy might crash!

Type: System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stracktrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EBPredictioner.EventHandlers.Spellbook_OnCastSpell(Spellbook sender, SpellbookCastSpellEventArgs args)
   at EloBuddy.Spellbook.OnSpellbookCastSpellNative(Obj_AI_Base* A_0, Spellbook* A_1, Vector3f* A_2, Vector3f* A_3, UInt32 A_4, Int32 A_5)
========================================

**Comment by berbb** [comment]
Shouldn't effect much.
