### ISSUE TITLE
VHR errors

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#556]
```
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.Common.Dash.LSIsDashing(Obj_AI_Base unit)
   at VayneHunter_Reborn.Modules.ModuleList.Condemn.FlashCondemn.OnExecute()
   at VayneHunter_Reborn.VHR.OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================
```

**Comment by berbb** [comment]
Pushed an update on Berb.Common that should fix this, although if it does happen again ignore it, it shouldn't effect much.
