### ISSUE TITLE
Port AIO dosn't load

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#578]
I have the common, but when it load, there is only portAIO misc and it's an empty menu... yesterday it was working fine, but now... tryed with every champs
PS : Evade# make crash when taking Taric's E or when Azir ult (I'm not sure about Azir ult)

**Comment by yorik100** [comment]
[EloBuddy] EloBuddy (Releases/6.13 - Date: Jul  5 2016 Time: 16:10:20) loading..
.
Loading EloBuddy
Loading EloBuddy.SDK
Loading 1 Addon
[13:50:51 - Info] ----------------------------------
[13:50:51 - Info] Loading SDK Bootstrap
[13:50:51 - Info] ----------------------------------
System.IO.FileNotFoundException: File not found.
   at System.Drawing.Text.PrivateFontCollection.AddMemoryFont(IntPtr memory, Int
32 length)
   at EloBuddy.SDK.Rendering.Text.LoadFont(Byte[] fontData)
   at EloBuddy.SDK.Rendering.Text..cctor()
[13:50:51 - Info] EntityManager.Heroes: Allies (1) Enemies (0)
[13:50:51 - Info] SpellDatabase loaded.
[13:50:51 - Info] TargetSelector loaded.
[13:50:51 - Info] Orbwalker loaded.
[13:50:51 - Info] Prediction loaded.
[13:50:51 - Info] DamageLibrary loaded.
[13:50:51 - Info] SummonerSpells loaded.
[13:50:51 - Info] ----------------------------------
[13:50:51 - Info] SDK Bootstrap fully loaded!
[13:50:51 - Info] ----------------------------------
[13:50:51.7966858 - Info]: (Init) -> [-- SDK Bootstrap Loading --]
[13:50:51.7976858 - Info]: (Init) -> [SDK Bootstrap] Resources Initialized.
[13:50:51.8336879 - Info]: (Init) -> [SDK Bootstrap] GameObjects Initialized.
[13:50:51.8336879 - Info]: (Init) -> [SDK Bootstrap] Damage Library Initialized.

[13:50:51.8346879 - Info]: (Init) -> [-- SDK Bootstrap Loading --]
[13:50:51 - Warn] Failed to notify OnLoadingComlete listener!
System.Reflection.TargetInvocationException: Exception has been thrown by the ta
rget of an invocation. ---> System.NullReferenceException: Object reference not
set to an instance of an object.
   at EloBuddy.SDK.Menu.ValueContainer..ctor(String addonId, String serializatio
nId)
   at EloBuddy.SDK.Menu.AddonContainer.AddMenu(Button button, String addonId, St
ring uniqueMenuId, String longTitle, Int32 index)
   at EloBuddy.SDK.Menu.Menu..ctor(String displayName, String addonId, String un
iqueMenuId, String longTitle, Menu parent)
   at EloBuddy.SDK.Menu.MainMenu.AddMenu(String displayName, String uniqueMenuId
, String longTitle)
   at PortAIO.Utility.Loader.Menu()
   at PortAIO.Init.Initialize(EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at EloBuddy.SDK.Events.Loading.CallLoadingComplete()

**Comment by berbb** [comment]
Have you updated everything?

**Comment by yorik100** [comment]
Updated and reinstalled

**Comment by yorik100** [comment]
FIXED by removing PortAIO menu save
